#!/usr/bin/env node
// =============================================================================
//  Claude Universal Custom Proxy
//
//  Local HTTP gateway that lets Claude Desktop / Claude Code talk to
//  Anthropic-compatible AND OpenAI-compatible upstream providers (Ollama Cloud,
//  HuggingFace Inference Router, NVIDIA NIM, DeepSeek, Moonshot/Kimi, Z.AI/GLM,
//  Xiaomi MiMo, OpenAI, Gemini, Qwen, Anthropic).
//
//  ── Design notes ───────────────────────────────────────────────────────────
//  All model metadata lives in one registry: NATIVE_ANTHROPIC_MODELS (the real
//  Claude family) + PROVIDER_MODELS (every free/served model on Ollama Cloud,
//  HuggingFace Inference Router, and NVIDIA NIM). The routing tables (modelMap,
//  modelRoutes, modelAliases, visibleModels) are derived from that registry at
//  module load, so adding a model means editing one list.
//
//  Each provider model is advertised under a single brand alias:
//    ollama-<name>   e.g. ollama-deepseek-v3.1, ollama-qwen3-coder-480b
//    hf-<name>       e.g. hf-deepseek-r1, hf-llama-3.1-8b-instruct
//    nim-<name>      e.g. nim-llama-3.1-8b-instruct, nim-gpt-oss-120b
//  No claude- prefix on third-party models, so Claude Desktop's Cowork picker
//  (which hides claude-* ids containing a foundation-model brand keyword) shows
//  every one of them, and they're findable by typing the model name.
//
//  The catalog is generated from each provider's live /v1/models endpoint plus a
//  per-model chat probe — see scripts/probe-models.mjs + generate-registry.mjs.
//  Subscription-gated and non-chat (embedding/guard/rerank) models are excluded.
// =============================================================================

import dotenv from 'dotenv';
dotenv.config();

import http from 'node:http';
import https from 'node:https';
import { Transform } from 'node:stream';
import { StringDecoder } from 'node:string_decoder';
import { fileURLToPath } from 'node:url';

export const SERVER_NAME = 'claude-universal-custom-proxy';
export const SERVER_VERSION = '0.10.0';

// ─────────────────────────────────────────────────────────────────────────────
//  Debug logging — gated by DEBUG_PROXY=true (default off)
// ─────────────────────────────────────────────────────────────────────────────
const DEBUG = String(process.env.DEBUG_PROXY || '').toLowerCase() === 'true';

function debugLog(...args) {
  if (DEBUG) console.log(...args);
}

function debugBlock(title, lines) {
  if (!DEBUG) return;
  console.log(`\n========== ${title} ==========`);
  for (const line of lines) console.log(line);
  console.log('='.repeat(title.length + 22) + '\n');
}

// ─────────────────────────────────────────────────────────────────────────────
//  Constants
// ─────────────────────────────────────────────────────────────────────────────
const HOP_BY_HOP_HEADERS = new Set([
  'connection', 'keep-alive', 'proxy-authenticate', 'proxy-authorization',
  'te', 'trailer', 'transfer-encoding', 'upgrade',
]);

const MODEL_VALUE_KEYS = new Set(['default_model', 'id', 'model', 'model_id', 'name']);
const MODEL_ARRAY_KEYS = new Set(['inferenceModels', 'inference_models', 'models']);
const DEFAULT_REQUEST_BODY_LIMIT_BYTES = 50 * 1024 * 1024;

const CLAUDE_DATED_SUFFIX = /-(\d{8})$/;

// ─────────────────────────────────────────────────────────────────────────────
//  Model registry — single source of truth.
//
//  Every entry is { provider, alias, upstream }:
//    provider – key into the providers config (ollama | huggingface | nvidia | …)
//    alias    – the id advertised in /v1/models and shown in the model picker
//    upstream – the exact model id sent to the provider's API
//
//  The catalog below was generated by querying each provider's own /v1/models
//  endpoint and then probing a 1-token chat completion per model
//  (scripts/probe-models.mjs + scripts/generate-registry.mjs). Only models the
//  provider actually serves AND that responded 200 on the free tier are listed.
//  Subscription-gated Ollama Cloud models (HTTP 403) and non-chat models
//  (embeddings, rerankers, safety guards, OCR/parse) are excluded.
//
//  Refresh:  npm run models:probe   (writes scripts/.model-probe.json)
//            npm run models:discover (lists each provider's live catalog)
// ─────────────────────────────────────────────────────────────────────────────

// Native Anthropic family — reachable only when ANTHROPIC_API_KEY is set.
// Otherwise DEFAULT_CLAUDE_FAMILY_FALLBACK reroutes haiku/sonnet/opus (and the
// dated/internal variants Claude Desktop emits) to a free Ollama Cloud alias.
const NATIVE_ANTHROPIC_MODELS = Object.freeze([
  'claude-haiku-4-5',
  'claude-sonnet-4-6',
  'claude-opus-4-7',
  'claude-sonnet-4-5',
  'claude-opus-4-1',
]);

const PROVIDER_MODELS = Object.freeze([
// ===== Ollama Cloud (free tier — probe-verified 200) =====
  { provider: 'ollama', alias: 'ollama-cogito-2.1-671b', upstream: "cogito-2.1:671b" },
  { provider: 'ollama', alias: 'ollama-devstral-2-123b', upstream: "devstral-2:123b" },
  { provider: 'ollama', alias: 'ollama-devstral-small-2-24b', upstream: "devstral-small-2:24b" },
  { provider: 'ollama', alias: 'ollama-gemma3-12b', upstream: "gemma3:12b" },
  { provider: 'ollama', alias: 'ollama-gemma3-27b', upstream: "gemma3:27b" },
  { provider: 'ollama', alias: 'ollama-gemma3-4b', upstream: "gemma3:4b" },
  { provider: 'ollama', alias: 'ollama-gemma4-31b', upstream: "gemma4:31b" },
  { provider: 'ollama', alias: 'ollama-glm-4.6', upstream: "glm-4.6" },
  { provider: 'ollama', alias: 'ollama-glm-4.7', upstream: "glm-4.7" },
  { provider: 'ollama', alias: 'ollama-gpt-oss-120b', upstream: "gpt-oss:120b" },
  { provider: 'ollama', alias: 'ollama-gpt-oss-20b', upstream: "gpt-oss:20b" },
  { provider: 'ollama', alias: 'ollama-minimax-m2', upstream: "minimax-m2" },
  { provider: 'ollama', alias: 'ollama-minimax-m2.1', upstream: "minimax-m2.1" },
  { provider: 'ollama', alias: 'ollama-minimax-m2.5', upstream: "minimax-m2.5" },
  { provider: 'ollama', alias: 'ollama-ministral-3-14b', upstream: "ministral-3:14b" },
  { provider: 'ollama', alias: 'ollama-ministral-3-3b', upstream: "ministral-3:3b" },
  { provider: 'ollama', alias: 'ollama-ministral-3-8b', upstream: "ministral-3:8b" },
  { provider: 'ollama', alias: 'ollama-nemotron-3-nano-30b', upstream: "nemotron-3-nano:30b" },
  { provider: 'ollama', alias: 'ollama-nemotron-3-super', upstream: "nemotron-3-super" },
  { provider: 'ollama', alias: 'ollama-qwen3-coder-next', upstream: "qwen3-coder-next" },
  { provider: 'ollama', alias: 'ollama-qwen3-coder-480b', upstream: "qwen3-coder:480b" },
  { provider: 'ollama', alias: 'ollama-qwen3-next-80b', upstream: "qwen3-next:80b" },
  { provider: 'ollama', alias: 'ollama-qwen3-vl-235b', upstream: "qwen3-vl:235b" },
  { provider: 'ollama', alias: 'ollama-qwen3-vl-235b-instruct', upstream: "qwen3-vl:235b-instruct" },
  { provider: 'ollama', alias: 'ollama-rnj-1-8b', upstream: "rnj-1:8b" },

// ===== HuggingFace Inference Router (served catalog, chat-capable) =====
  { provider: 'huggingface', alias: 'hf-aya-expanse-32b', upstream: "CohereLabs/aya-expanse-32b" },
  { provider: 'huggingface', alias: 'hf-aya-vision-32b', upstream: "CohereLabs/aya-vision-32b" },
  { provider: 'huggingface', alias: 'hf-c4ai-command-a-03-2025', upstream: "CohereLabs/c4ai-command-a-03-2025" },
  { provider: 'huggingface', alias: 'hf-c4ai-command-r-08-2024', upstream: "CohereLabs/c4ai-command-r-08-2024" },
  { provider: 'huggingface', alias: 'hf-c4ai-command-r7b-12-2024', upstream: "CohereLabs/c4ai-command-r7b-12-2024" },
  { provider: 'huggingface', alias: 'hf-c4ai-command-r7b-arabic-02-2025', upstream: "CohereLabs/c4ai-command-r7b-arabic-02-2025" },
  { provider: 'huggingface', alias: 'hf-command-a-reasoning-08-2025', upstream: "CohereLabs/command-a-reasoning-08-2025" },
  { provider: 'huggingface', alias: 'hf-tiny-aya-earth', upstream: "CohereLabs/tiny-aya-earth" },
  { provider: 'huggingface', alias: 'hf-tiny-aya-fire', upstream: "CohereLabs/tiny-aya-fire" },
  { provider: 'huggingface', alias: 'hf-tiny-aya-global', upstream: "CohereLabs/tiny-aya-global" },
  { provider: 'huggingface', alias: 'hf-tiny-aya-water', upstream: "CohereLabs/tiny-aya-water" },
  { provider: 'huggingface', alias: 'hf-rnj-1-instruct', upstream: "EssentialAI/rnj-1-instruct" },
  { provider: 'huggingface', alias: 'hf-minimax-m1-80k', upstream: "MiniMaxAI/MiniMax-M1-80k" },
  { provider: 'huggingface', alias: 'hf-minimax-m2', upstream: "MiniMaxAI/MiniMax-M2" },
  { provider: 'huggingface', alias: 'hf-minimax-m2.1', upstream: "MiniMaxAI/MiniMax-M2.1" },
  { provider: 'huggingface', alias: 'hf-minimax-m2.5', upstream: "MiniMaxAI/MiniMax-M2.5" },
  { provider: 'huggingface', alias: 'hf-minimax-m2.7', upstream: "MiniMaxAI/MiniMax-M2.7" },
  { provider: 'huggingface', alias: 'hf-hermes-2-pro-llama-3-8b', upstream: "NousResearch/Hermes-2-Pro-Llama-3-8B" },
  { provider: 'huggingface', alias: 'hf-qwq-32b', upstream: "Qwen/QwQ-32B" },
  { provider: 'huggingface', alias: 'hf-qwen2.5-72b-instruct', upstream: "Qwen/Qwen2.5-72B-Instruct" },
  { provider: 'huggingface', alias: 'hf-qwen2.5-7b-instruct', upstream: "Qwen/Qwen2.5-7B-Instruct" },
  { provider: 'huggingface', alias: 'hf-qwen2.5-coder-32b-instruct', upstream: "Qwen/Qwen2.5-Coder-32B-Instruct" },
  { provider: 'huggingface', alias: 'hf-qwen2.5-coder-3b-instruct', upstream: "Qwen/Qwen2.5-Coder-3B-Instruct" },
  { provider: 'huggingface', alias: 'hf-qwen2.5-coder-7b-instruct', upstream: "Qwen/Qwen2.5-Coder-7B-Instruct" },
  { provider: 'huggingface', alias: 'hf-qwen2.5-vl-72b-instruct', upstream: "Qwen/Qwen2.5-VL-72B-Instruct" },
  { provider: 'huggingface', alias: 'hf-qwen3-14b', upstream: "Qwen/Qwen3-14B" },
  { provider: 'huggingface', alias: 'hf-qwen3-235b-a22b', upstream: "Qwen/Qwen3-235B-A22B" },
  { provider: 'huggingface', alias: 'hf-qwen3-235b-a22b-instruct-2507', upstream: "Qwen/Qwen3-235B-A22B-Instruct-2507" },
  { provider: 'huggingface', alias: 'hf-qwen3-235b-a22b-thinking-2507', upstream: "Qwen/Qwen3-235B-A22B-Thinking-2507" },
  { provider: 'huggingface', alias: 'hf-qwen3-30b-a3b', upstream: "Qwen/Qwen3-30B-A3B" },
  { provider: 'huggingface', alias: 'hf-qwen3-32b', upstream: "Qwen/Qwen3-32B" },
  { provider: 'huggingface', alias: 'hf-qwen3-4b-instruct-2507', upstream: "Qwen/Qwen3-4B-Instruct-2507" },
  { provider: 'huggingface', alias: 'hf-qwen3-4b-thinking-2507', upstream: "Qwen/Qwen3-4B-Thinking-2507" },
  { provider: 'huggingface', alias: 'hf-qwen3-8b', upstream: "Qwen/Qwen3-8B" },
  { provider: 'huggingface', alias: 'hf-qwen3-coder-30b-a3b-instruct', upstream: "Qwen/Qwen3-Coder-30B-A3B-Instruct" },
  { provider: 'huggingface', alias: 'hf-qwen3-coder-480b-a35b-instruct', upstream: "Qwen/Qwen3-Coder-480B-A35B-Instruct" },
  { provider: 'huggingface', alias: 'hf-qwen3-coder-480b-a35b-instruct-fp8', upstream: "Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8" },
  { provider: 'huggingface', alias: 'hf-qwen3-coder-next', upstream: "Qwen/Qwen3-Coder-Next" },
  { provider: 'huggingface', alias: 'hf-qwen3-next-80b-a3b-instruct', upstream: "Qwen/Qwen3-Next-80B-A3B-Instruct" },
  { provider: 'huggingface', alias: 'hf-qwen3-next-80b-a3b-thinking', upstream: "Qwen/Qwen3-Next-80B-A3B-Thinking" },
  { provider: 'huggingface', alias: 'hf-qwen3-vl-235b-a22b-instruct', upstream: "Qwen/Qwen3-VL-235B-A22B-Instruct" },
  { provider: 'huggingface', alias: 'hf-qwen3-vl-235b-a22b-thinking', upstream: "Qwen/Qwen3-VL-235B-A22B-Thinking" },
  { provider: 'huggingface', alias: 'hf-qwen3-vl-30b-a3b-instruct', upstream: "Qwen/Qwen3-VL-30B-A3B-Instruct" },
  { provider: 'huggingface', alias: 'hf-qwen3-vl-30b-a3b-thinking', upstream: "Qwen/Qwen3-VL-30B-A3B-Thinking" },
  { provider: 'huggingface', alias: 'hf-qwen3-vl-8b-instruct', upstream: "Qwen/Qwen3-VL-8B-Instruct" },
  { provider: 'huggingface', alias: 'hf-qwen3.5-122b-a10b', upstream: "Qwen/Qwen3.5-122B-A10B" },
  { provider: 'huggingface', alias: 'hf-qwen3.5-27b', upstream: "Qwen/Qwen3.5-27B" },
  { provider: 'huggingface', alias: 'hf-qwen3.5-35b-a3b', upstream: "Qwen/Qwen3.5-35B-A3B" },
  { provider: 'huggingface', alias: 'hf-qwen3.5-397b-a17b', upstream: "Qwen/Qwen3.5-397B-A17B" },
  { provider: 'huggingface', alias: 'hf-qwen3.5-9b', upstream: "Qwen/Qwen3.5-9B" },
  { provider: 'huggingface', alias: 'hf-qwen3.6-35b-a3b', upstream: "Qwen/Qwen3.6-35B-A3B" },
  { provider: 'huggingface', alias: 'hf-l3-70b-euryale-v2.1', upstream: "Sao10K/L3-70B-Euryale-v2.1" },
  { provider: 'huggingface', alias: 'hf-l3-8b-lunaris-v1', upstream: "Sao10K/L3-8B-Lunaris-v1" },
  { provider: 'huggingface', alias: 'hf-l3-8b-stheno-v3.2', upstream: "Sao10K/L3-8B-Stheno-v3.2" },
  { provider: 'huggingface', alias: 'hf-mimo-v2-flash', upstream: "XiaomiMiMo/MiMo-V2-Flash" },
  { provider: 'huggingface', alias: 'hf-gemma-sea-lion-v4-27b-it', upstream: "aisingapore/Gemma-SEA-LION-v4-27B-IT" },
  { provider: 'huggingface', alias: 'hf-qwen-sea-lion-v4-32b-it', upstream: "aisingapore/Qwen-SEA-LION-v4-32B-IT" },
  { provider: 'huggingface', alias: 'hf-olmo-3-7b-instruct', upstream: "allenai/Olmo-3-7B-Instruct" },
  { provider: 'huggingface', alias: 'hf-wizardlm-2-8x22b', upstream: "alpindale/WizardLM-2-8x22B" },
  { provider: 'huggingface', alias: 'hf-ernie-4.5-300b-a47b-base-pt', upstream: "baidu/ERNIE-4.5-300B-A47B-Base-PT" },
  { provider: 'huggingface', alias: 'hf-ernie-4.5-vl-424b-a47b-base-pt', upstream: "baidu/ERNIE-4.5-VL-424B-A47B-Base-PT" },
  { provider: 'huggingface', alias: 'hf-cogito-671b-v2.1', upstream: "deepcogito/cogito-671b-v2.1" },
  { provider: 'huggingface', alias: 'hf-cogito-671b-v2.1-fp8', upstream: "deepcogito/cogito-671b-v2.1-FP8" },
  { provider: 'huggingface', alias: 'hf-deepseek-prover-v2-671b', upstream: "deepseek-ai/DeepSeek-Prover-V2-671B" },
  { provider: 'huggingface', alias: 'hf-deepseek-r1', upstream: "deepseek-ai/DeepSeek-R1" },
  { provider: 'huggingface', alias: 'hf-deepseek-r1-0528', upstream: "deepseek-ai/DeepSeek-R1-0528" },
  { provider: 'huggingface', alias: 'hf-deepseek-r1-distill-llama-70b', upstream: "deepseek-ai/DeepSeek-R1-Distill-Llama-70B" },
  { provider: 'huggingface', alias: 'hf-deepseek-r1-distill-llama-8b', upstream: "deepseek-ai/DeepSeek-R1-Distill-Llama-8B" },
  { provider: 'huggingface', alias: 'hf-deepseek-r1-distill-qwen-1.5b', upstream: "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B" },
  { provider: 'huggingface', alias: 'hf-deepseek-r1-distill-qwen-14b', upstream: "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B" },
  { provider: 'huggingface', alias: 'hf-deepseek-r1-distill-qwen-32b', upstream: "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B" },
  { provider: 'huggingface', alias: 'hf-deepseek-r1-distill-qwen-7b', upstream: "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B" },
  { provider: 'huggingface', alias: 'hf-deepseek-v3', upstream: "deepseek-ai/DeepSeek-V3" },
  { provider: 'huggingface', alias: 'hf-deepseek-v3-0324', upstream: "deepseek-ai/DeepSeek-V3-0324" },
  { provider: 'huggingface', alias: 'hf-deepseek-v3.1', upstream: "deepseek-ai/DeepSeek-V3.1" },
  { provider: 'huggingface', alias: 'hf-deepseek-v3.1-terminus', upstream: "deepseek-ai/DeepSeek-V3.1-Terminus" },
  { provider: 'huggingface', alias: 'hf-deepseek-v3.2', upstream: "deepseek-ai/DeepSeek-V3.2" },
  { provider: 'huggingface', alias: 'hf-deepseek-v3.2-exp', upstream: "deepseek-ai/DeepSeek-V3.2-Exp" },
  { provider: 'huggingface', alias: 'hf-deepseek-v4-flash', upstream: "deepseek-ai/DeepSeek-V4-Flash" },
  { provider: 'huggingface', alias: 'hf-deepseek-v4-pro', upstream: "deepseek-ai/DeepSeek-V4-Pro" },
  { provider: 'huggingface', alias: 'hf-dictalm-3.0-24b-thinking', upstream: "dicta-il/DictaLM-3.0-24B-Thinking" },
  { provider: 'huggingface', alias: 'hf-gemma-3-27b-it', upstream: "google/gemma-3-27b-it" },
  { provider: 'huggingface', alias: 'hf-gemma-3n-e4b-it', upstream: "google/gemma-3n-E4B-it" },
  { provider: 'huggingface', alias: 'hf-gemma-4-26b-a4b-it', upstream: "google/gemma-4-26B-A4B-it" },
  { provider: 'huggingface', alias: 'hf-gemma-4-31b-it', upstream: "google/gemma-4-31B-it" },
  { provider: 'huggingface', alias: 'hf-ling-2.6-1t', upstream: "inclusionAI/Ling-2.6-1T" },
  { provider: 'huggingface', alias: 'hf-arch-router-1.5b', upstream: "katanemo/Arch-Router-1.5B" },
  { provider: 'huggingface', alias: 'hf-llama-3.1-70b-instruct', upstream: "meta-llama/Llama-3.1-70B-Instruct" },
  { provider: 'huggingface', alias: 'hf-llama-3.1-8b-instruct', upstream: "meta-llama/Llama-3.1-8B-Instruct" },
  { provider: 'huggingface', alias: 'hf-llama-3.2-1b-instruct', upstream: "meta-llama/Llama-3.2-1B-Instruct" },
  { provider: 'huggingface', alias: 'hf-llama-3.3-70b-instruct', upstream: "meta-llama/Llama-3.3-70B-Instruct" },
  { provider: 'huggingface', alias: 'hf-llama-4-maverick-17b-128e-instruct', upstream: "meta-llama/Llama-4-Maverick-17B-128E-Instruct" },
  { provider: 'huggingface', alias: 'hf-llama-4-maverick-17b-128e-instruct-fp8', upstream: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8" },
  { provider: 'huggingface', alias: 'hf-llama-4-scout-17b-16e-instruct', upstream: "meta-llama/Llama-4-Scout-17B-16E-Instruct" },
  { provider: 'huggingface', alias: 'hf-meta-llama-3-70b-instruct', upstream: "meta-llama/Meta-Llama-3-70B-Instruct" },
  { provider: 'huggingface', alias: 'hf-meta-llama-3-8b-instruct', upstream: "meta-llama/Meta-Llama-3-8B-Instruct" },
  { provider: 'huggingface', alias: 'hf-kimi-k2-instruct', upstream: "moonshotai/Kimi-K2-Instruct" },
  { provider: 'huggingface', alias: 'hf-kimi-k2-instruct-0905', upstream: "moonshotai/Kimi-K2-Instruct-0905" },
  { provider: 'huggingface', alias: 'hf-kimi-k2-thinking', upstream: "moonshotai/Kimi-K2-Thinking" },
  { provider: 'huggingface', alias: 'hf-kimi-k2.5', upstream: "moonshotai/Kimi-K2.5" },
  { provider: 'huggingface', alias: 'hf-kimi-k2.6', upstream: "moonshotai/Kimi-K2.6" },
  { provider: 'huggingface', alias: 'hf-gpt-oss-120b', upstream: "openai/gpt-oss-120b" },
  { provider: 'huggingface', alias: 'hf-gpt-oss-20b', upstream: "openai/gpt-oss-20b" },
  { provider: 'huggingface', alias: 'hf-gemma-4-31b-it-pearl', upstream: "pearl-ai/Gemma-4-31B-it-pearl" },
  { provider: 'huggingface', alias: 'hf-step-3.5-flash', upstream: "stepfun-ai/Step-3.5-Flash" },
  { provider: 'huggingface', alias: 'hf-apertus-70b-instruct-2509', upstream: "swiss-ai/Apertus-70B-Instruct-2509" },
  { provider: 'huggingface', alias: 'hf-apertus-8b-instruct-2509', upstream: "swiss-ai/Apertus-8B-Instruct-2509" },
  { provider: 'huggingface', alias: 'hf-eurollm-22b-instruct-2512', upstream: "utter-project/EuroLLM-22B-Instruct-2512" },
  { provider: 'huggingface', alias: 'hf-autoglm-phone-9b-multilingual', upstream: "zai-org/AutoGLM-Phone-9B-Multilingual" },
  { provider: 'huggingface', alias: 'hf-glm-4-32b-0414', upstream: "zai-org/GLM-4-32B-0414" },
  { provider: 'huggingface', alias: 'hf-glm-4.5', upstream: "zai-org/GLM-4.5" },
  { provider: 'huggingface', alias: 'hf-glm-4.5-air', upstream: "zai-org/GLM-4.5-Air" },
  { provider: 'huggingface', alias: 'hf-glm-4.5v', upstream: "zai-org/GLM-4.5V" },
  { provider: 'huggingface', alias: 'hf-glm-4.5v-fp8', upstream: "zai-org/GLM-4.5V-FP8" },
  { provider: 'huggingface', alias: 'hf-glm-4.6', upstream: "zai-org/GLM-4.6" },
  { provider: 'huggingface', alias: 'hf-glm-4.6-fp8', upstream: "zai-org/GLM-4.6-FP8" },
  { provider: 'huggingface', alias: 'hf-glm-4.6v', upstream: "zai-org/GLM-4.6V" },
  { provider: 'huggingface', alias: 'hf-glm-4.6v-fp8', upstream: "zai-org/GLM-4.6V-FP8" },
  { provider: 'huggingface', alias: 'hf-glm-4.6v-flash', upstream: "zai-org/GLM-4.6V-Flash" },
  { provider: 'huggingface', alias: 'hf-glm-4.7', upstream: "zai-org/GLM-4.7" },
  { provider: 'huggingface', alias: 'hf-glm-4.7-fp8', upstream: "zai-org/GLM-4.7-FP8" },
  { provider: 'huggingface', alias: 'hf-glm-4.7-flash', upstream: "zai-org/GLM-4.7-Flash" },
  { provider: 'huggingface', alias: 'hf-glm-5', upstream: "zai-org/GLM-5" },
  { provider: 'huggingface', alias: 'hf-glm-5.1', upstream: "zai-org/GLM-5.1" },
  { provider: 'huggingface', alias: 'hf-glm-5.1-fp8', upstream: "zai-org/GLM-5.1-FP8" },

// ===== NVIDIA NIM (free tier) =====
  { provider: 'nvidia', alias: 'nim-dracarys-llama-3.1-70b-instruct', upstream: "abacusai/dracarys-llama-3.1-70b-instruct" },
  { provider: 'nvidia', alias: 'nim-gemma-2-2b-it', upstream: "google/gemma-2-2b-it" },
  { provider: 'nvidia', alias: 'nim-gemma-3n-e2b-it', upstream: "google/gemma-3n-e2b-it" },
  { provider: 'nvidia', alias: 'nim-gemma-3n-e4b-it', upstream: "google/gemma-3n-e4b-it" },
  { provider: 'nvidia', alias: 'nim-llama-3.1-70b-instruct', upstream: "meta/llama-3.1-70b-instruct" },
  { provider: 'nvidia', alias: 'nim-llama-3.1-8b-instruct', upstream: "meta/llama-3.1-8b-instruct" },
  { provider: 'nvidia', alias: 'nim-llama-3.2-11b-vision-instruct', upstream: "meta/llama-3.2-11b-vision-instruct" },
  { provider: 'nvidia', alias: 'nim-llama-3.2-1b-instruct', upstream: "meta/llama-3.2-1b-instruct" },
  { provider: 'nvidia', alias: 'nim-llama-3.2-3b-instruct', upstream: "meta/llama-3.2-3b-instruct" },
  { provider: 'nvidia', alias: 'nim-llama-3.3-70b-instruct', upstream: "meta/llama-3.3-70b-instruct" },
  { provider: 'nvidia', alias: 'nim-llama-4-maverick-17b-128e-instruct', upstream: "meta/llama-4-maverick-17b-128e-instruct" },
  { provider: 'nvidia', alias: 'nim-ministral-14b-instruct-2512', upstream: "mistralai/ministral-14b-instruct-2512" },
  { provider: 'nvidia', alias: 'nim-mistral-large-3-675b-instruct-2512', upstream: "mistralai/mistral-large-3-675b-instruct-2512" },
  { provider: 'nvidia', alias: 'nim-mistral-medium-3.5-128b', upstream: "mistralai/mistral-medium-3.5-128b" },
  { provider: 'nvidia', alias: 'nim-mistral-nemotron', upstream: "mistralai/mistral-nemotron" },
  { provider: 'nvidia', alias: 'nim-mistral-small-4-119b-2603', upstream: "mistralai/mistral-small-4-119b-2603" },
  { provider: 'nvidia', alias: 'nim-mixtral-8x22b-instruct-v0.1', upstream: "mistralai/mixtral-8x22b-instruct-v0.1" },
  { provider: 'nvidia', alias: 'nim-mixtral-8x7b-instruct-v0.1', upstream: "mistralai/mixtral-8x7b-instruct-v0.1" },
  { provider: 'nvidia', alias: 'nim-kimi-k2.6', upstream: "moonshotai/kimi-k2.6" },
  { provider: 'nvidia', alias: 'nim-ising-calibration-1-35b-a3b', upstream: "nvidia/ising-calibration-1-35b-a3b" },
  { provider: 'nvidia', alias: 'nim-llama-3.1-nemotron-nano-8b-v1', upstream: "nvidia/llama-3.1-nemotron-nano-8b-v1" },
  { provider: 'nvidia', alias: 'nim-llama-3.1-nemotron-nano-vl-8b-v1', upstream: "nvidia/llama-3.1-nemotron-nano-vl-8b-v1" },
  { provider: 'nvidia', alias: 'nim-llama-3.3-nemotron-super-49b-v1.5', upstream: "nvidia/llama-3.3-nemotron-super-49b-v1.5" },
  { provider: 'nvidia', alias: 'nim-nemotron-3-nano-30b-a3b', upstream: "nvidia/nemotron-3-nano-30b-a3b" },
  { provider: 'nvidia', alias: 'nim-nemotron-3-nano-omni-30b-a3b-reasoning', upstream: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning" },
  { provider: 'nvidia', alias: 'nim-nemotron-3-super-120b-a12b', upstream: "nvidia/nemotron-3-super-120b-a12b" },
  { provider: 'nvidia', alias: 'nim-nemotron-mini-4b-instruct', upstream: "nvidia/nemotron-mini-4b-instruct" },
  { provider: 'nvidia', alias: 'nim-nemotron-nano-12b-v2-vl', upstream: "nvidia/nemotron-nano-12b-v2-vl" },
  { provider: 'nvidia', alias: 'nim-nvidia-nemotron-nano-9b-v2', upstream: "nvidia/nvidia-nemotron-nano-9b-v2" },
  { provider: 'nvidia', alias: 'nim-gpt-oss-120b', upstream: "openai/gpt-oss-120b" },
  { provider: 'nvidia', alias: 'nim-gpt-oss-20b', upstream: "openai/gpt-oss-20b" },
  { provider: 'nvidia', alias: 'nim-qwen3-coder-480b-a35b-instruct', upstream: "qwen/qwen3-coder-480b-a35b-instruct" },
  { provider: 'nvidia', alias: 'nim-qwen3-next-80b-a3b-instruct', upstream: "qwen/qwen3-next-80b-a3b-instruct" },
  { provider: 'nvidia', alias: 'nim-qwen3-next-80b-a3b-thinking', upstream: "qwen/qwen3-next-80b-a3b-thinking" },
  { provider: 'nvidia', alias: 'nim-sarvam-m', upstream: "sarvamai/sarvam-m" },
  { provider: 'nvidia', alias: 'nim-step-3.5-flash', upstream: "stepfun-ai/step-3.5-flash" },
  { provider: 'nvidia', alias: 'nim-stockmark-2-100b-instruct', upstream: "stockmark/stockmark-2-100b-instruct" },
  { provider: 'nvidia', alias: 'nim-solar-10.7b-instruct', upstream: "upstage/solar-10.7b-instruct" },
]);

const {
  DEFAULT_MODEL_MAP,
  DEFAULT_MODEL_ROUTES,
  DEFAULT_MODEL_ALIASES,
  DEFAULT_VISIBLE_MODELS,
  DEFAULT_HIDDEN_ALIASES,
} = buildDefaultRegistry();

// Backward-compatible exports.
export { DEFAULT_MODEL_MAP, DEFAULT_MODEL_ROUTES, DEFAULT_MODEL_ALIASES };
export const DEFAULT_CLAUDE_MODEL_MAP = DEFAULT_MODEL_MAP;

function buildDefaultRegistry() {
  const map = {};
  const routes = {};
  const aliases = {};
  const visible = [];

  for (const model of NATIVE_ANTHROPIC_MODELS) {
    map[model] = model;
    routes[model] = 'anthropic';
    aliases[model] = model;
    visible.push(model);
  }

  for (const m of PROVIDER_MODELS) {
    map[m.alias] = m.upstream;
    routes[m.alias] = m.provider;
    // First alias wins as the display name for a given upstream id (used to
    // rewrite response.model back to the picker alias). The same upstream id can
    // be served by two providers (e.g. openai/gpt-oss-120b on both HF and NIM);
    // buildResponseModelMap still prefers the alias the client actually sent.
    if (!aliases[m.upstream]) aliases[m.upstream] = m.alias;
    visible.push(m.alias);
  }

  return {
    DEFAULT_MODEL_MAP: Object.freeze(map),
    DEFAULT_MODEL_ROUTES: Object.freeze(routes),
    DEFAULT_MODEL_ALIASES: Object.freeze(aliases),
    DEFAULT_VISIBLE_MODELS: Object.freeze(visible),
    DEFAULT_HIDDEN_ALIASES: new Set(),
  };
}

// ─────────────────────────────────────────────────────────────────────────────
//  Claude family fallback
//
//  When the incoming request asks for a haiku/sonnet/opus model that has no
//  exact match in modelMap AND the anthropic provider has no API key, we
//  re-route to a configured alias from the open providers.  Override via
//  CLAUDE_HAIKU_MODEL / CLAUDE_SONNET_MODEL / CLAUDE_OPUS_MODEL env vars.
// ─────────────────────────────────────────────────────────────────────────────
export const DEFAULT_CLAUDE_FAMILY_FALLBACK = Object.freeze({
  haiku: 'ollama-gpt-oss-20b',
  sonnet: 'ollama-qwen3-coder-480b',
  opus: 'ollama-gpt-oss-120b',
});

export function resolveClaudeFamily(model) {
  if (typeof model !== 'string') return null;
  if (/^claude-haiku\b/.test(model)) return 'haiku';
  if (/^claude-sonnet\b/.test(model)) return 'sonnet';
  if (/^claude-opus\b/.test(model)) return 'opus';
  return null;
}

export function stripClaudeDate(model) {
  return typeof model === 'string' ? model.replace(CLAUDE_DATED_SUFFIX, '') : model;
}

/**
 * Map a request model id to a usable alias, applying:
 *   1. Exact modelMap hit (unless it would route to anthropic-without-key)
 *   2. Date-stripped modelMap hit (same caveat)
 *   3. Claude family fallback (haiku/sonnet/opus → configured alias)
 *   4. Pass-through (lets defaultProvider handle it)
 */
export function resolveClaudeAlias(model, config) {
  if (typeof model !== 'string' || !model) return model;

  const anthropicHasKey = Boolean(config.providers?.anthropic?.upstreamApiKey);
  const isUsable = (alias) =>
    Boolean(alias && config.modelMap[alias])
    && !(config.modelRoutes?.[alias] === 'anthropic' && !anthropicHasKey);

  if (isUsable(model)) return model;

  const stripped = stripClaudeDate(model);
  if (stripped !== model && isUsable(stripped)) return stripped;

  const family = resolveClaudeFamily(model);
  if (family && !anthropicHasKey) {
    const fallback = config.claudeFamilyFallback?.[family];
    if (fallback && config.modelMap[fallback]) return fallback;
  }

  return model;
}

/** Back-compat shim — older test harnesses import this. */
export function resolveModelForUpstream(model, config) {
  if (typeof model !== 'string' || !model) {
    return { upstreamModel: model, requestAlias: model, family: null };
  }
  const requestAlias = resolveClaudeAlias(model, config);
  const upstreamModel = config.modelMap?.[requestAlias] || requestAlias;
  return {
    upstreamModel,
    requestAlias,
    family: resolveClaudeFamily(model) || resolveClaudeFamily(requestAlias),
  };
}

// ─────────────────────────────────────────────────────────────────────────────
//  Config loading
// ─────────────────────────────────────────────────────────────────────────────
export function loadConfig(env = process.env) {
  env = mergeAdvancedEnv(env);

  const port = parseInteger(env.PORT || env.CLAUDE_DEEPSEEK_PROXY_PORT, 8787);

  const modelMap = {
    ...DEFAULT_MODEL_MAP,
    ...parseStringMap(env.MODEL_MAP || env.CLAUDE_MODEL_MAP, 'MODEL_MAP'),
  };
  const modelRoutes = normalizeProviderRoutes({
    ...DEFAULT_MODEL_ROUTES,
    ...parseStringMap(env.MODEL_ROUTES, 'MODEL_ROUTES'),
  });
  const modelAliases = {
    ...DEFAULT_MODEL_ALIASES,
    ...parseStringMap(env.MODEL_ALIASES, 'MODEL_ALIASES'),
  };
  const claudeFamilyFallback = {
    ...DEFAULT_CLAUDE_FAMILY_FALLBACK,
    ...(env.CLAUDE_HAIKU_MODEL ? { haiku: env.CLAUDE_HAIKU_MODEL } : {}),
    ...(env.CLAUDE_SONNET_MODEL ? { sonnet: env.CLAUDE_SONNET_MODEL } : {}),
    ...(env.CLAUDE_OPUS_MODEL ? { opus: env.CLAUDE_OPUS_MODEL } : {}),
  };

  return {
    port,
    baseUrl: env.BASE_URL || env.PROXY_BASE_URL || 'http://127.0.0.1:8787',
    defaultProvider: normalizeProviderName(env.DEFAULT_PROVIDER || 'ollama'),
    providers: {
      deepseek: {
        upstreamBaseUrl: new URL(env.DEEPSEEK_BASE_URL || env.UPSTREAM_BASE_URL || 'https://api.deepseek.com/anthropic'),
        upstreamApiKey: env.DEEPSEEK_API_KEY || env.UPSTREAM_API_KEY || '',
        format: 'anthropic',
        authScheme: 'bearer',
      },
      moonshot: {
        upstreamBaseUrl: new URL(env.MOONSHOT_BASE_URL || env.KIMI_BASE_URL || 'https://api.moonshot.cn/anthropic'),
        upstreamApiKey: env.MOONSHOT_API_KEY || env.KIMI_API_KEY || '',
        format: 'anthropic',
        authScheme: 'bearer',
      },
      glm: {
        upstreamBaseUrl: new URL(env.GLM_BASE_URL || env.ZAI_BASE_URL || env.ZHIPU_BASE_URL || 'https://api.z.ai/api/anthropic'),
        upstreamApiKey: env.GLM_API_KEY || env.ZAI_API_KEY || env.ZHIPU_API_KEY || '',
        format: 'anthropic',
        authScheme: 'bearer',
      },
      xiaomi: {
        upstreamBaseUrl: new URL(env.XIAOMI_BASE_URL || env.MIMO_BASE_URL || 'https://api.xiaomimimo.com/anthropic'),
        upstreamApiKey: env.XIAOMI_API_KEY || env.MIMO_API_KEY || '',
        format: 'anthropic',
        authScheme: 'bearer',
      },
      openai: {
        upstreamBaseUrl: new URL(env.OPENAI_BASE_URL || 'https://api.openai.com/v1'),
        upstreamApiKey: env.OPENAI_API_KEY || '',
        format: 'openai-chat',
        authScheme: 'bearer',
        maxTokensField: 'max_completion_tokens',
      },
      gemini: {
        upstreamBaseUrl: new URL(env.GEMINI_BASE_URL || env.GOOGLE_BASE_URL || 'https://generativelanguage.googleapis.com/v1beta/openai'),
        upstreamApiKey: env.GEMINI_API_KEY || env.GOOGLE_API_KEY || '',
        format: 'openai-chat',
        authScheme: 'bearer',
        maxTokensField: 'max_tokens',
      },
      qwen: {
        upstreamBaseUrl: new URL(env.QWEN_BASE_URL || env.DASHSCOPE_BASE_URL || 'https://dashscope.aliyuncs.com/compatible-mode/v1'),
        upstreamApiKey: env.QWEN_API_KEY || env.DASHSCOPE_API_KEY || '',
        format: 'openai-chat',
        authScheme: 'bearer',
        maxTokensField: 'max_tokens',
      },
      ollama: {
        upstreamBaseUrl: new URL(env.OLLAMA_BASE_URL || 'https://ollama.com/v1'),
        upstreamApiKey: env.OLLAMA_API_KEY || '',
        format: 'openai-chat',
        authScheme: 'bearer',
        maxTokensField: 'max_tokens',
      },
      huggingface: {
        upstreamBaseUrl: new URL(env.HUGGINGFACE_BASE_URL || env.HF_BASE_URL || 'https://router.huggingface.co/v1'),
        upstreamApiKey: env.HUGGINGFACE_API_KEY || env.HF_API_KEY || env.HF_TOKEN || '',
        format: 'openai-chat',
        authScheme: 'bearer',
        maxTokensField: 'max_tokens',
      },
      nvidia: {
        upstreamBaseUrl: new URL(env.NVIDIA_BASE_URL || env.NIM_BASE_URL || 'https://integrate.api.nvidia.com/v1'),
        upstreamApiKey: env.NVIDIA_API_KEY || env.NVAPI_KEY || env.NIM_API_KEY || '',
        format: 'openai-chat',
        authScheme: 'bearer',
        maxTokensField: 'max_tokens',
      },
      anthropic: {
        upstreamBaseUrl: new URL(env.ANTHROPIC_BASE_URL || 'https://api.anthropic.com'),
        upstreamApiKey: env.ANTHROPIC_API_KEY || '',
        format: 'anthropic',
        authScheme: 'x-api-key',
        anthropicVersion: env.ANTHROPIC_VERSION || '2023-06-01',
      },
    },
    modelMap,
    modelRoutes,
    modelAliases,
    claudeFamilyFallback,
    visibleModels: DEFAULT_VISIBLE_MODELS,
    hiddenAliases: DEFAULT_HIDDEN_ALIASES,
    rewriteResponses: parseBoolean(env.REWRITE_RESPONSES, true),
    requestBodyLimitBytes: parseInteger(env.REQUEST_BODY_LIMIT_BYTES, DEFAULT_REQUEST_BODY_LIMIT_BYTES),
  };
}

// ─────────────────────────────────────────────────────────────────────────────
//  Server
// ─────────────────────────────────────────────────────────────────────────────
export function createProxyServer(config = loadConfig()) {
  const normalizedConfig = normalizeConfig(config);

  return http.createServer(async (clientReq, clientRes) => {
    const requestStart = Date.now();
    debugBlock('INCOMING REQUEST', [
      `Method: ${clientReq.method}`,
      `URL: ${clientReq.url}`,
      `User-Agent: ${clientReq.headers['user-agent'] || ''}`,
      `Content-Type: ${clientReq.headers['content-type'] || ''}`,
    ]);

    try {
      // /healthz — local probe.
      if (clientReq.method === 'GET' && clientReq.url === '/healthz') {
        sendJson(clientRes, 200, {
          ok: true,
          baseUrl: normalizedConfig.baseUrl,
          defaultProvider: normalizedConfig.defaultProvider,
          providers: getProviderStatus(normalizedConfig.providers),
          modelMap: normalizedConfig.modelMap,
          modelAliases: normalizedConfig.modelAliases,
          modelRoutes: normalizedConfig.modelRoutes,
          claudeFamilyFallback: normalizedConfig.claudeFamilyFallback,
          visibleModels: normalizedConfig.visibleModels,
          rewriteResponses: normalizedConfig.rewriteResponses,
        });
        return;
      }

      // /v1/models — picker catalog.
      if (clientReq.method === 'GET' && isModelsRequest(clientReq.url)) {
        handleModelsRequest(clientReq, clientRes, normalizedConfig);
        return;
      }

      // /v1/messages/count_tokens — answered locally.
      if (clientReq.method === 'POST' && isCountTokensRequest(clientReq.url)) {
        await handleCountTokensRequest(clientReq, clientRes, normalizedConfig);
        return;
      }

      // Everything else — forward to upstream after model resolution.
      const rawBody = await readRequestBody(clientReq, normalizedConfig.requestBodyLimitBytes);
      const contentType = String(clientReq.headers['content-type'] || '');
      const prepared = prepareRequest(rawBody, contentType, normalizedConfig);
      const target = buildTargetUrl(prepared.provider, clientReq.url || '/');
      const headers = buildUpstreamHeaders(clientReq.headers, target, prepared.body, prepared.provider);
      forwardRequest({
        target,
        method: clientReq.method || 'GET',
        headers,
        body: prepared.body,
        clientRes,
        rewriteResponses: normalizedConfig.rewriteResponses,
        responseModelMap: prepared.responseModelMap,
        provider: prepared.provider,
        requestStart,
      });
    } catch (error) {
      const statusCode = error.statusCode || 500;
      console.error(`[${SERVER_NAME}] ${statusCode} ${error.message}`);
      sendJson(clientRes, statusCode, { error: String(error.message || error) });
    }
  });
}

function isModelsRequest(rawUrl = '/') {
  const pathname = new URL(rawUrl, 'http://127.0.0.1').pathname;
  return pathname === '/v1/models' || pathname.startsWith('/v1/models/');
}

function isCountTokensRequest(rawUrl = '/') {
  const pathname = new URL(rawUrl, 'http://127.0.0.1').pathname;
  return pathname === '/v1/messages/count_tokens'
    || pathname.endsWith('/v1/messages/count_tokens');
}

const MODELS_CREATED_AT = '2026-01-01T00:00:00Z';

function handleModelsRequest(req, res, config) {
  const pathname = new URL(req.url || '/', 'http://127.0.0.1').pathname;
  const visible = listVisibleModels(config);

  if (pathname === '/v1/models') {
    sendJson(res, 200, {
      data: visible,
      first_id: visible[0]?.id || null,
      has_more: false,
      last_id: visible.at(-1)?.id || null,
    });
    return;
  }

  // /v1/models/{id} — return a single descriptor. Allow lookup for ANY known
  // alias, including hidden ones, so legacy configs continue to work.
  const modelId = decodeURIComponent(pathname.slice('/v1/models/'.length));
  if (!config.modelMap[modelId]) {
    sendJson(res, 404, { error: `Unknown model: ${modelId}` });
    return;
  }
  sendJson(res, 200, {
    type: 'model',
    id: modelId,
    display_name: modelId,
    created_at: MODELS_CREATED_AT,
  });
}

function listVisibleModels(config) {
  const visible = Array.isArray(config.visibleModels) && config.visibleModels.length
    ? config.visibleModels
    : Object.keys(config.modelMap);
  const hidden = config.hiddenAliases instanceof Set ? config.hiddenAliases : new Set();

  return visible
    .filter((id) => !hidden.has(id))
    .map((id) => ({
      type: 'model',
      id,
      display_name: id,
      created_at: MODELS_CREATED_AT,
    }));
}

async function handleCountTokensRequest(req, res, config) {
  const rawBody = await readRequestBody(req, config.requestBodyLimitBytes);
  let payload = {};
  if (rawBody.length > 0) {
    try { payload = JSON.parse(rawBody.toString('utf8')); } catch { payload = {}; }
  }
  const inputTokens = estimateAnthropicTokenCount(payload);
  debugBlock('COUNT TOKENS (LOCAL)', [
    `Model: ${payload.model || '(none)'}`,
    `Estimated input_tokens: ${inputTokens}`,
  ]);
  sendJson(res, 200, { input_tokens: inputTokens });
}

function estimateAnthropicTokenCount(payload) {
  const parts = [];
  for (const block of toArray(payload.system)) {
    if (typeof block === 'string') parts.push(block);
    else if (block?.text) parts.push(block.text);
  }
  for (const message of toArray(payload.messages)) {
    const content = message?.content;
    if (typeof content === 'string') {
      parts.push(content);
    } else if (Array.isArray(content)) {
      for (const block of content) {
        if (typeof block === 'string') parts.push(block);
        else if (block?.text) parts.push(block.text);
        else if (block?.content) parts.push(stringifyUnknownContent(block.content));
      }
    }
  }
  for (const tool of toArray(payload.tools)) {
    if (tool?.name) parts.push(tool.name);
    if (tool?.description) parts.push(tool.description);
    if (tool?.input_schema) parts.push(JSON.stringify(tool.input_schema));
  }
  const totalChars = parts.reduce((sum, value) => sum + (value?.length || 0), 0);
  return Math.max(1, Math.ceil(totalChars / 4));
}

function toArray(value) {
  return Array.isArray(value) ? value : (value === undefined || value === null ? [] : [value]);
}

// ─────────────────────────────────────────────────────────────────────────────
//  Request preparation — applies smart resolver + body rewriting.
// ─────────────────────────────────────────────────────────────────────────────
function prepareRequest(rawBody, contentType, config) {
  if (rawBody.length === 0 || !isJsonContentType(contentType)) {
    return { body: rawBody, provider: resolveProvider('', '', config), responseModelMap: config.modelAliases };
  }

  const parsed = JSON.parse(rawBody.toString('utf8'));
  const incomingModel = typeof parsed?.model === 'string' ? parsed.model : '';

  // Apply family fallback / date stripping BEFORE map rewriting so dated and
  // generic Claude names get re-routed to a working upstream.
  const resolvedAlias = resolveClaudeAlias(incomingModel, config);
  if (resolvedAlias && resolvedAlias !== incomingModel) parsed.model = resolvedAlias;

  const rewritten = rewriteModelValues(parsed, config.modelMap);
  const requestModels = collectModelValues(parsed);
  const upstreamModels = collectModelValues(rewritten);
  const requestAlias = requestModels[0] || '';
  const upstreamModel = upstreamModels[0] || requestAlias;
  const provider = resolveProvider(upstreamModel, requestAlias, config);

  debugBlock('MODEL ROUTING', [
    `Incoming model: ${incomingModel || '(none)'}`,
    `Resolved alias: ${requestAlias || '(none)'}`,
    `Upstream model: ${upstreamModel || '(none)'}`,
    `Provider: ${provider?.name || ''} (${provider?.upstreamBaseUrl?.host || ''})`,
    `Format: ${provider?.format || ''}`,
  ]);

  const responseModelMap = buildResponseModelMap(
    upstreamModels,
    config.modelAliases,
    requestModels,
    config.modelMap,
  );
  // If we family-fell-back, keep the original alias visible in responses too.
  if (incomingModel && upstreamModel && incomingModel !== requestAlias) {
    responseModelMap[upstreamModel] = incomingModel;
  }

  return {
    body: formatRequestBody(rewritten, provider),
    provider,
    responseModelMap,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
//  Upstream forwarding & response handling
// ─────────────────────────────────────────────────────────────────────────────
function forwardRequest(opts) {
  const { target, method, headers, body, clientRes, rewriteResponses, responseModelMap, provider, requestStart } = opts;
  const transport = target.protocol === 'https:' ? https : http;

  debugBlock('FORWARDING REQUEST', [
    `Method: ${method}`,
    `Target: ${target.href}`,
    `Body Size: ${body.length}`,
  ]);

  const upstreamReq = transport.request(
    {
      protocol: target.protocol,
      hostname: target.hostname,
      port: target.port || undefined,
      method,
      path: `${target.pathname}${target.search}`,
      headers,
    },
    (upstreamRes) => {
      const duration = Date.now() - (requestStart || Date.now());
      debugBlock('UPSTREAM RESPONSE', [
        `Duration: ${duration}ms`,
        `Status: ${upstreamRes.statusCode} ${upstreamRes.statusMessage || ''}`,
        `Content-Type: ${upstreamRes.headers['content-type'] || ''}`,
      ]);
      handleUpstreamResponse(upstreamRes, clientRes, { rewriteResponses, responseModelMap, provider });
    },
  );

  upstreamReq.on('error', (error) => {
    console.error(`[${SERVER_NAME}] upstream error: ${error.message}`);
    if (!clientRes.headersSent) sendJson(clientRes, 502, { error: `Upstream request failed: ${error.message}` });
    else clientRes.destroy(error);
  });

  upstreamReq.end(body);
}

function handleUpstreamResponse(upstreamRes, clientRes, config) {
  const headers = sanitizeResponseHeaders(upstreamRes.headers);
  const contentType = String(headers['content-type'] || '');

  if (config.provider?.format === 'openai-chat' && isSuccessfulStatus(upstreamRes.statusCode)) {
    handleOpenAIChatResponse(upstreamRes, clientRes, { ...config, headers, contentType });
    return;
  }

  if (config.rewriteResponses && isJsonContentType(contentType)) {
    collectResponse(upstreamRes)
      .then((body) => {
        if (!isSuccessfulStatus(upstreamRes.statusCode) && DEBUG) {
          console.log('\n========== UPSTREAM ERROR BODY ==========');
          console.log(body.toString('utf8'));
          console.log('=========================================\n');
        }
        const rewritten = rewriteJsonResponseBody(body, config.responseModelMap);
        headers['content-length'] = String(rewritten.length);
        clientRes.writeHead(upstreamRes.statusCode || 502, upstreamRes.statusMessage, headers);
        clientRes.end(rewritten);
      })
      .catch((error) => {
        if (!clientRes.headersSent) sendJson(clientRes, 502, { error: `Upstream response handling failed: ${error.message}` });
        else clientRes.destroy(error);
      });
    return;
  }

  clientRes.writeHead(upstreamRes.statusCode || 502, upstreamRes.statusMessage, headers);
  if (config.rewriteResponses && isTextualContentType(contentType)) {
    upstreamRes.pipe(createReplaceStream(config.responseModelMap)).pipe(clientRes);
    return;
  }
  upstreamRes.pipe(clientRes);
}

// ─────────────────────────────────────────────────────────────────────────────
//  Anthropic ↔ OpenAI-chat body translation
// ─────────────────────────────────────────────────────────────────────────────
function formatRequestBody(rewrittenBody, provider) {
  return provider.format === 'openai-chat'
    ? Buffer.from(JSON.stringify(toOpenAIChatRequest(rewrittenBody, provider)))
    : Buffer.from(JSON.stringify(rewrittenBody));
}

function toOpenAIChatRequest(body, provider) {
  const request = { model: body.model, messages: [] };

  const systemContent = toOpenAIContent(body.system, 'system');
  if (!isEmptyOpenAIContent(systemContent)) {
    request.messages.push({ role: 'system', content: systemContent });
  }

  for (const message of Array.isArray(body.messages) ? body.messages : []) {
    request.messages.push({
      role: toOpenAIMessageRole(message.role),
      content: toOpenAIContent(message.content, message.role),
    });
  }

  copyDefined(request, body, 'temperature');
  copyDefined(request, body, 'top_p');
  copyDefined(request, body, 'stream');
  copyDefined(request, body, 'presence_penalty');
  copyDefined(request, body, 'frequency_penalty');

  if (body.max_tokens !== undefined) {
    request[provider.maxTokensField || 'max_tokens'] = body.max_tokens;
  }
  if (Array.isArray(body.stop_sequences) && body.stop_sequences.length > 0) {
    request.stop = body.stop_sequences;
  }
  if (typeof body.metadata?.user_id === 'string' && body.metadata.user_id) {
    request.user = body.metadata.user_id;
  }
  return request;
}

function toOpenAIMessageRole(role) {
  return role === 'assistant' ? 'assistant' : 'user';
}

function isEmptyOpenAIContent(content) {
  return Array.isArray(content) ? content.length === 0 : content === '';
}

function copyDefined(target, source, key) {
  if (source[key] !== undefined) target[key] = source[key];
}

function toOpenAIContent(content, role) {
  if (content === undefined || content === null) return '';
  if (typeof content === 'string') return content;
  if (!Array.isArray(content)) return stringifyUnknownContent(content);

  const parts = content.flatMap((part) => toOpenAIContentPart(part));
  const hasNonTextPart = parts.some((part) => typeof part !== 'string' && part.type !== 'text');
  if (role !== 'user' || !hasNonTextPart) {
    return parts.map((part) => (typeof part === 'string' ? part : part.text || '')).join('');
  }
  return parts.map((part) => (typeof part === 'string' ? { type: 'text', text: part } : part));
}

function toOpenAIContentPart(part) {
  if (typeof part === 'string') return [part];
  if (!part || typeof part !== 'object') return [String(part ?? '')];
  if (part.type === 'text') return [{ type: 'text', text: part.text || '' }];
  if (part.type === 'image' && part.source?.type === 'base64') {
    return [{
      type: 'image_url',
      image_url: { url: `data:${part.source.media_type || 'image/png'};base64,${part.source.data || ''}` },
    }];
  }
  if (part.type === 'tool_result') return [{ type: 'text', text: toTextContent(part.content) }];
  if (part.text) return [{ type: 'text', text: String(part.text) }];
  return [{ type: 'text', text: stringifyUnknownContent(part) }];
}

function toTextContent(content) {
  if (typeof content === 'string') return content;
  if (Array.isArray(content)) {
    return content.map((item) => {
      if (typeof item === 'string') return item;
      if (item?.type === 'text') return item.text || '';
      return stringifyUnknownContent(item);
    }).join('');
  }
  return stringifyUnknownContent(content);
}

function stringifyUnknownContent(value) {
  if (value === undefined || value === null) return '';
  if (typeof value === 'string') return value;
  try { return JSON.stringify(value); } catch { return String(value); }
}

// ─────────────────────────────────────────────────────────────────────────────
//  OpenAI-chat → Anthropic Messages response translation
// ─────────────────────────────────────────────────────────────────────────────
function handleOpenAIChatResponse(upstreamRes, clientRes, config) {
  const responseModelMap = config.rewriteResponses ? config.responseModelMap : {};

  if (isJsonContentType(config.contentType)) {
    collectResponse(upstreamRes)
      .then((body) => {
        const converted = convertOpenAIChatJsonResponse(body, responseModelMap);
        config.headers['content-type'] = 'application/json; charset=utf-8';
        config.headers['content-length'] = String(converted.length);
        clientRes.writeHead(upstreamRes.statusCode || 502, upstreamRes.statusMessage, config.headers);
        clientRes.end(converted);
      })
      .catch((error) => {
        if (!clientRes.headersSent) sendJson(clientRes, 502, { error: `OpenAI-compatible response handling failed: ${error.message}` });
        else clientRes.destroy(error);
      });
    return;
  }

  clientRes.writeHead(upstreamRes.statusCode || 502, upstreamRes.statusMessage, {
    ...config.headers,
    'content-type': 'text/event-stream; charset=utf-8',
  });
  upstreamRes.pipe(createOpenAIChatSseToAnthropicStream(responseModelMap)).pipe(clientRes);
}

function convertOpenAIChatJsonResponse(body, responseModelMap) {
  if (body.length === 0) return body;
  const parsed = JSON.parse(body.toString('utf8'));
  const choice = parsed.choices?.[0];
  if (!choice) return Buffer.from(JSON.stringify(rewriteModelValues(parsed, responseModelMap)));

  const text = openAIMessageText(choice.message);
  const message = {
    id: parsed.id || 'msg_openai_proxy',
    type: 'message',
    role: 'assistant',
    model: rewriteModelName(parsed.model || '', responseModelMap),
    content: text ? [{ type: 'text', text }] : [],
    stop_reason: toAnthropicStopReason(choice.finish_reason),
    stop_sequence: null,
    usage: toAnthropicUsage(parsed.usage),
  };
  return Buffer.from(JSON.stringify(message));
}

function openAIMessageText(message) {
  if (!message) return '';
  if (typeof message.content === 'string') return message.content;
  if (Array.isArray(message.content)) {
    return message.content.map((part) => {
      if (typeof part === 'string') return part;
      if (part?.type === 'text') return part.text || '';
      if (part?.text) return String(part.text);
      if (part?.refusal) return String(part.refusal);
      return '';
    }).join('');
  }
  return message.refusal || '';
}

function createOpenAIChatSseToAnthropicStream(responseModelMap) {
  const decoder = new StringDecoder('utf8');
  const state = {
    buffer: '',
    messageStarted: false,
    contentBlockStarted: false,
    stopped: false,
    id: 'msg_openai_proxy',
    model: '',
    stopReason: 'end_turn',
    usage: { input_tokens: 0, output_tokens: 0 },
  };
  return new Transform({
    transform(chunk, _encoding, callback) {
      state.buffer += decoder.write(chunk).replace(/\r\n/g, '\n');
      processOpenAISseBuffer(this, state, responseModelMap);
      callback();
    },
    flush(callback) {
      state.buffer += decoder.end().replace(/\r\n/g, '\n');
      processOpenAISseBuffer(this, state, responseModelMap, true);
      stopAnthropicStream(this, state);
      callback();
    },
  });
}

function processOpenAISseBuffer(stream, state, responseModelMap, flush = false) {
  while (true) {
    const separatorIndex = state.buffer.indexOf('\n\n');
    if (separatorIndex === -1) break;
    const eventText = state.buffer.slice(0, separatorIndex);
    state.buffer = state.buffer.slice(separatorIndex + 2);
    handleOpenAISseEvent(stream, eventText, state, responseModelMap);
  }
  if (flush && state.buffer.trim()) {
    handleOpenAISseEvent(stream, state.buffer, state, responseModelMap);
    state.buffer = '';
  }
}

function handleOpenAISseEvent(stream, eventText, state, responseModelMap) {
  const data = eventText.split('\n')
    .filter((line) => line.startsWith('data:'))
    .map((line) => line.slice(5).trimStart())
    .join('\n')
    .trim();
  if (!data) return;
  if (data === '[DONE]') { stopAnthropicStream(stream, state); return; }

  let parsed;
  try { parsed = JSON.parse(data); } catch { return; }

  startAnthropicStream(stream, state, parsed, responseModelMap);
  const choice = parsed.choices?.[0];
  if (!choice) {
    if (parsed.usage) state.usage = toAnthropicUsage(parsed.usage);
    return;
  }
  if (choice.finish_reason) state.stopReason = toAnthropicStopReason(choice.finish_reason);
  const text = openAIStreamDeltaText(choice.delta);
  if (text) {
    if (!state.contentBlockStarted) {
      pushSse(stream, 'content_block_start', {
        type: 'content_block_start', index: 0,
        content_block: { type: 'text', text: '' },
      });
      state.contentBlockStarted = true;
    }
    pushSse(stream, 'content_block_delta', {
      type: 'content_block_delta', index: 0,
      delta: { type: 'text_delta', text },
    });
  }
  if (parsed.usage) state.usage = toAnthropicUsage(parsed.usage);
}

function startAnthropicStream(stream, state, chunk, responseModelMap) {
  if (state.messageStarted) return;
  state.id = chunk.id || state.id;
  state.model = rewriteModelName(chunk.model || state.model, responseModelMap);
  pushSse(stream, 'message_start', {
    type: 'message_start',
    message: {
      id: state.id, type: 'message', role: 'assistant', model: state.model,
      content: [], stop_reason: null, stop_sequence: null, usage: state.usage,
    },
  });
  state.messageStarted = true;
}

function stopAnthropicStream(stream, state) {
  if (state.stopped) return;
  if (!state.messageStarted) startAnthropicStream(stream, state, {}, {});
  if (state.contentBlockStarted) {
    pushSse(stream, 'content_block_stop', { type: 'content_block_stop', index: 0 });
  }
  pushSse(stream, 'message_delta', {
    type: 'message_delta',
    delta: { stop_reason: state.stopReason, stop_sequence: null },
    usage: { output_tokens: state.usage.output_tokens || 0 },
  });
  pushSse(stream, 'message_stop', { type: 'message_stop' });
  state.stopped = true;
}

function pushSse(stream, event, payload) {
  stream.push(`event: ${event}\ndata: ${JSON.stringify(payload)}\n\n`);
}

function openAIStreamDeltaText(delta) {
  if (!delta) return '';
  if (typeof delta.content === 'string') return delta.content;
  if (Array.isArray(delta.content)) {
    return delta.content.map((part) => {
      if (typeof part === 'string') return part;
      if (part?.type === 'text') return part.text || '';
      if (part?.text) return String(part.text);
      return '';
    }).join('');
  }
  return '';
}

function toAnthropicUsage(usage = {}) {
  return {
    input_tokens: usage.prompt_tokens ?? usage.input_tokens ?? 0,
    output_tokens: usage.completion_tokens ?? usage.output_tokens ?? 0,
  };
}

function toAnthropicStopReason(reason) {
  if (reason === 'length') return 'max_tokens';
  if (reason === 'tool_calls' || reason === 'function_call') return 'tool_use';
  return 'end_turn';
}

function rewriteModelName(model, responseModelMap) {
  return responseModelMap[model] || model;
}

function rewriteJsonResponseBody(body, responseModelMap) {
  if (body.length === 0) return body;
  let parsed;
  try { parsed = JSON.parse(body.toString('utf8')); }
  catch { return body; }
  return Buffer.from(JSON.stringify(rewriteModelValues(parsed, responseModelMap)));
}

// ─────────────────────────────────────────────────────────────────────────────
//  Model value walking — rewrite / collect every "model"-shaped field in a
//  nested JSON tree.
// ─────────────────────────────────────────────────────────────────────────────
export function rewriteModelValues(value, modelMap, keyName = '') {
  if (typeof value === 'string') {
    return (MODEL_VALUE_KEYS.has(keyName) || MODEL_ARRAY_KEYS.has(keyName))
      ? (modelMap[value] || value)
      : value;
  }
  if (Array.isArray(value)) return value.map((item) => rewriteModelValues(item, modelMap, keyName));
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value).map(([key, item]) => [key, rewriteModelValues(item, modelMap, key)]),
    );
  }
  return value;
}

export function createReplaceStream(modelMap) {
  const entries = Object.entries(modelMap).sort((a, b) => b[0].length - a[0].length);
  const decoder = new StringDecoder('utf8');
  let buffer = '';
  return new Transform({
    transform(chunk, _encoding, callback) {
      buffer += decoder.write(chunk);
      const emitEnd = buffer.lastIndexOf('\n');
      if (emitEnd === -1) { callback(); return; }
      this.push(replaceAllModels(buffer.slice(0, emitEnd + 1), entries));
      buffer = buffer.slice(emitEnd + 1);
      callback();
    },
    flush(callback) {
      this.push(replaceAllModels(buffer + decoder.end(), entries));
      callback();
    },
  });
}

function replaceAllModels(text, entries) {
  let output = text;
  for (const [from, to] of entries) output = output.replaceAll(from, to);
  return output;
}

function collectModelValues(value, keyName = '') {
  if (typeof value === 'string') {
    return (MODEL_VALUE_KEYS.has(keyName) || MODEL_ARRAY_KEYS.has(keyName)) ? [value] : [];
  }
  if (Array.isArray(value)) return value.flatMap((item) => collectModelValues(item, keyName));
  if (value && typeof value === 'object') {
    return Object.entries(value).flatMap(([key, item]) => collectModelValues(item, key));
  }
  return [];
}

function buildResponseModelMap(upstreamModels, modelAliases, requestModels = [], modelMap = {}) {
  const selected = {};
  for (const requestModel of requestModels) {
    const upstreamModel = modelMap[requestModel] || requestModel;
    if (upstreamModels.includes(upstreamModel)) selected[upstreamModel] = requestModel;
  }
  for (const model of upstreamModels) {
    if (!selected[model] && modelAliases[model]) selected[model] = modelAliases[model];
  }
  return Object.keys(selected).length > 0 ? selected : { ...modelAliases };
}

// ─────────────────────────────────────────────────────────────────────────────
//  Header & URL building
// ─────────────────────────────────────────────────────────────────────────────
function buildUpstreamHeaders(clientHeaders, target, body, provider) {
  const headers = {};

  for (const [key, value] of Object.entries(clientHeaders)) {
    const lowerKey = key.toLowerCase();
    if (HOP_BY_HOP_HEADERS.has(lowerKey) || lowerKey === 'host' || lowerKey === 'content-length') continue;
    headers[lowerKey] = value;
  }

  headers.host = target.host;
  headers['content-length'] = String(body.length);
  headers['accept-encoding'] = 'identity';

  if (provider.format === 'openai-chat') {
    delete headers['anthropic-version'];
    delete headers['anthropic-beta'];
    delete headers['x-api-key'];
    headers['content-type'] = 'application/json';
  }

  // Substitute the upstream API key — this is what stops Claude Desktop's
  // gateway-provided "Bearer dummy-…" from leaking through.
  if (provider.upstreamApiKey) {
    delete headers.authorization;
    delete headers['x-api-key'];
    if (provider.authScheme === 'x-api-key') {
      headers['x-api-key'] = provider.upstreamApiKey;
    } else {
      headers.authorization = `Bearer ${provider.upstreamApiKey}`;
    }
  }

  if (provider.authScheme === 'x-api-key' && provider.anthropicVersion) {
    headers['anthropic-version'] = headers['anthropic-version'] || provider.anthropicVersion;
  }

  return headers;
}

function sanitizeResponseHeaders(upstreamHeaders) {
  const headers = {};
  for (const [key, value] of Object.entries(upstreamHeaders)) {
    const lowerKey = key.toLowerCase();
    if (!HOP_BY_HOP_HEADERS.has(lowerKey)) headers[lowerKey] = value;
  }
  delete headers['content-encoding'];
  delete headers['content-length'];
  return headers;
}

function buildTargetUrl(provider, incomingUrl) {
  const source = new URL(incomingUrl, 'http://localhost');
  const target = new URL(provider.upstreamBaseUrl.href);
  const basePath = target.pathname.replace(/\/$/, '');
  let sourcePath = source.pathname;

  if (provider.format === 'openai-chat') {
    if (sourcePath === '/v1/messages' || sourcePath.endsWith('/v1/messages')) {
      sourcePath = '/chat/completions';
    } else if (sourcePath === '/v1/messages/count_tokens' || sourcePath.endsWith('/v1/messages/count_tokens')) {
      sourcePath = '/chat/completions';
    } else if (basePath.endsWith('/v1') && sourcePath.startsWith('/v1/')) {
      sourcePath = sourcePath.slice(3);
    }
  } else if (basePath.endsWith('/v1') && sourcePath.startsWith('/v1/')) {
    sourcePath = sourcePath.slice(3);
  }

  target.pathname = `${basePath}${sourcePath}`.replace(/\/{2,}/g, '/');
  target.search = provider.format === 'openai-chat' ? '' : source.search;
  return target;
}

// ─────────────────────────────────────────────────────────────────────────────
//  Stream helpers
// ─────────────────────────────────────────────────────────────────────────────
async function readRequestBody(req, limitBytes) {
  const chunks = [];
  let totalLength = 0;
  for await (const chunk of req) {
    totalLength += chunk.length;
    if (totalLength > limitBytes) {
      const error = new Error(`Request body exceeds ${limitBytes} bytes`);
      error.statusCode = 413;
      throw error;
    }
    chunks.push(chunk);
  }
  return Buffer.concat(chunks);
}

async function collectResponse(res) {
  const chunks = [];
  for await (const chunk of res) chunks.push(chunk);
  return Buffer.concat(chunks);
}

function sendJson(res, statusCode, payload) {
  const body = Buffer.from(JSON.stringify(payload));
  res.writeHead(statusCode, {
    'content-type': 'application/json; charset=utf-8',
    'content-length': String(body.length),
  });
  res.end(body);
}

// ─────────────────────────────────────────────────────────────────────────────
//  Env parsing
// ─────────────────────────────────────────────────────────────────────────────
function mergeAdvancedEnv(env) {
  return { ...parseAdvancedEnv(env.ADVANCED_ENV), ...env };
}

function parseAdvancedEnv(raw) {
  if (!raw) return {};
  const trimmed = String(raw).trim();
  if (!trimmed) return {};
  const parsed = JSON.parse(trimmed);
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
    throw new Error('ADVANCED_ENV must be a JSON object');
  }
  return Object.fromEntries(Object.entries(parsed).map(([key, value]) => {
    if (!key || value === null || typeof value === 'object') {
      throw new Error('ADVANCED_ENV keys must be non-empty and values must be strings, numbers, or booleans');
    }
    return [key, String(value)];
  }));
}

function parseStringMap(raw, name) {
  if (!raw) return {};
  let trimmed = String(raw).trim();
  if (!trimmed) return {};

  if (trimmed.startsWith('{')) {
    trimmed = trimmed.replace(/\r?\n/g, ' ').replace(/\s+/g, ' ').replace(/,\s*}/g, '}');
    try { return normalizeStringMap(JSON.parse(trimmed), name); }
    catch { throw new Error(`${name} contains invalid JSON`); }
  }

  const parsed = Object.fromEntries(trimmed.split(',').map((entry) => {
    const i = entry.indexOf('=');
    if (i === -1) throw new Error(`${name} entries must use from=to format`);
    return [entry.slice(0, i).trim(), entry.slice(i + 1).trim()];
  }));
  return normalizeStringMap(parsed, name);
}

function normalizeStringMap(value, name) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error(`${name} must be a JSON object or from=to list`);
  }
  return Object.fromEntries(Object.entries(value).map(([from, to]) => {
    if (!from || typeof to !== 'string' || !to) {
      throw new Error(`${name} keys and values must be non-empty strings`);
    }
    return [from, to];
  }));
}

// ─────────────────────────────────────────────────────────────────────────────
//  Config normalization & provider resolution
// ─────────────────────────────────────────────────────────────────────────────
const DEFAULT_PROVIDER_PRIORITY = [
  'ollama', 'huggingface', 'nvidia',
  'openai', 'gemini', 'qwen',
  'glm', 'moonshot', 'xiaomi',
  'anthropic', 'deepseek',
];

function pickFallbackDefaultProvider(providers, requested) {
  if (providers[requested]?.upstreamApiKey) return requested;
  for (const name of DEFAULT_PROVIDER_PRIORITY) {
    if (providers[name]?.upstreamApiKey) return name;
  }
  return requested;
}

function normalizeConfig(config) {
  const providers = normalizeProviders(config);
  const requested = normalizeProviderName(
    config.defaultProvider || (providers.ollama ? 'ollama' : Object.keys(providers)[0]),
  );
  if (!providers[requested]) throw new Error(`No upstream provider configured for ${requested}`);
  const defaultProvider = pickFallbackDefaultProvider(providers, requested);
  if (defaultProvider !== requested) {
    console.error(`[${SERVER_NAME}] DEFAULT_PROVIDER=${requested} has no API key; falling back to ${defaultProvider}`);
  }
  return {
    ...config,
    baseUrl: config.baseUrl || `http://127.0.0.1:${config.port || 8787}`,
    defaultProvider,
    providers,
    modelMap: config.modelMap || DEFAULT_MODEL_MAP,
    modelAliases: config.modelAliases || DEFAULT_MODEL_ALIASES,
    modelRoutes: normalizeProviderRoutes(config.modelRoutes || DEFAULT_MODEL_ROUTES),
    claudeFamilyFallback: config.claudeFamilyFallback || DEFAULT_CLAUDE_FAMILY_FALLBACK,
    visibleModels: config.visibleModels || DEFAULT_VISIBLE_MODELS,
    hiddenAliases: config.hiddenAliases || DEFAULT_HIDDEN_ALIASES,
    rewriteResponses: config.rewriteResponses ?? true,
    requestBodyLimitBytes: config.requestBodyLimitBytes || DEFAULT_REQUEST_BODY_LIMIT_BYTES,
  };
}

function normalizeProviders(config) {
  if (config.providers) {
    return Object.fromEntries(Object.entries(config.providers).map(([name, provider]) => [
      normalizeProviderName(name),
      { ...normalizeProvider(provider), name: normalizeProviderName(name) },
    ]));
  }
  if (config.upstreamBaseUrl) {
    return {
      deepseek: {
        ...normalizeProvider({ upstreamBaseUrl: config.upstreamBaseUrl, upstreamApiKey: config.upstreamApiKey || '' }),
        name: 'deepseek',
      },
    };
  }
  throw new Error('At least one upstream provider must be configured');
}

function normalizeProvider(provider) {
  if (!provider?.upstreamBaseUrl) throw new Error('Provider upstreamBaseUrl is required');
  return {
    upstreamBaseUrl: provider.upstreamBaseUrl instanceof URL ? provider.upstreamBaseUrl : new URL(provider.upstreamBaseUrl),
    upstreamApiKey: provider.upstreamApiKey || '',
    format: normalizeProviderFormat(provider.format || 'anthropic'),
    authScheme: normalizeAuthScheme(provider.authScheme || 'bearer'),
    anthropicVersion: provider.anthropicVersion || '2023-06-01',
    maxTokensField: provider.maxTokensField || 'max_tokens',
  };
}

function normalizeProviderFormat(format) {
  const f = String(format || '').trim().toLowerCase();
  if (f === 'anthropic' || f === 'openai-chat') return f;
  throw new Error(`Unsupported provider format: ${format}`);
}

function normalizeAuthScheme(authScheme) {
  const s = String(authScheme || '').trim().toLowerCase();
  if (s === 'bearer' || s === 'x-api-key') return s;
  throw new Error(`Unsupported auth scheme: ${authScheme}`);
}

function normalizeProviderRoutes(modelRoutes) {
  return Object.fromEntries(
    Object.entries(modelRoutes).map(([model, provider]) => [model, normalizeProviderName(provider)]),
  );
}

function normalizeProviderName(provider) {
  const n = String(provider || '').trim().toLowerCase();
  if (n === 'kimi') return 'moonshot';
  if (n === 'hf') return 'huggingface';
  if (n === 'nim' || n === 'nemo' || n === 'nvapi') return 'nvidia';
  return n;
}

/**
 * Pick the provider that handles a (upstreamModel, requestAlias) pair.
 * Alias takes precedence over upstream id, so e.g. "claude-opus-ol-ds-v3.1"
 * routes to ollama even though "deepseek-v3.1:671b-cloud" isn't in the route
 * table.
 */
function resolveProvider(upstreamModel, requestAlias, config) {
  const name = (requestAlias && config.modelRoutes[requestAlias])
    || (upstreamModel && config.modelRoutes[upstreamModel])
    || config.defaultProvider;
  const provider = config.providers[name];
  if (!provider) throw new Error(`No upstream provider configured for ${name}`);
  return provider;
}

function getProviderStatus(providers) {
  return Object.fromEntries(Object.entries(providers).map(([name, p]) => [name, {
    upstreamBaseUrl: redactUrl(p.upstreamBaseUrl),
    hasApiKey: Boolean(p.upstreamApiKey),
    format: p.format,
    authScheme: p.authScheme,
  }]));
}

// ─────────────────────────────────────────────────────────────────────────────
//  Misc helpers
// ─────────────────────────────────────────────────────────────────────────────
function parseInteger(raw, fallback) {
  if (raw === undefined || raw === null || raw === '') return fallback;
  const v = Number.parseInt(String(raw), 10);
  if (!Number.isFinite(v) || v <= 0) throw new Error(`Invalid positive integer: ${raw}`);
  return v;
}

function parseBoolean(raw, fallback) {
  if (raw === undefined || raw === null || raw === '') return fallback;
  const lower = String(raw).toLowerCase();
  if (['1', 'true', 'yes', 'on'].includes(lower)) return true;
  if (['0', 'false', 'no', 'off'].includes(lower)) return false;
  throw new Error(`Invalid boolean: ${raw}`);
}

function isSuccessfulStatus(statusCode) {
  return Number.isInteger(statusCode) && statusCode >= 200 && statusCode < 300;
}

function isJsonContentType(contentType) {
  return /\bapplication\/(?:[\w.+-]+\+)?json\b/i.test(contentType);
}

function isTextualContentType(contentType) {
  return /^text\//i.test(contentType) || /\bjson\b/i.test(contentType);
}

function redactUrl(url) {
  const u = new URL(url.href);
  u.username = '';
  u.password = '';
  return u.href;
}

// ─────────────────────────────────────────────────────────────────────────────
//  CLI entry
// ─────────────────────────────────────────────────────────────────────────────
const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];

if (isMain) {
  try {
    const config = loadConfig();
    const server = createProxyServer(config);

    server.on('error', (error) => {
      if (error.code === 'EADDRINUSE') {
        console.error(`[${SERVER_NAME}] port ${config.port} is already in use`);
        process.exit(0);
      }
      console.error(`[${SERVER_NAME}] failed: ${error.message}`);
      process.exit(1);
    });

    server.listen(config.port, '127.0.0.1', () => {
      console.log('========================================');
      console.log(`  CLAUDE UNIVERSAL CUSTOM PROXY v${SERVER_VERSION}`);
      console.log('========================================');
      console.log(`Listening:         http://127.0.0.1:${config.port}`);
      console.log(`Gateway base URL:  ${config.baseUrl}`);
      console.log(`Rewrite responses: ${config.rewriteResponses}`);
      console.log(`Debug logging:     ${DEBUG ? 'on' : 'off'} (DEBUG_PROXY=true to enable)`);
      console.log('----------------------------------------');
      console.log(' Providers (✔ = API key set):');
      for (const [name, p] of Object.entries(config.providers)) {
        console.log(`  ${p.upstreamApiKey ? '✔' : ' '} ${name.padEnd(12)} ${p.upstreamBaseUrl.href}  [${p.format}]`);
      }
      console.log('----------------------------------------');
      console.log(' Family fallback (used when ANTHROPIC_API_KEY is empty):');
      for (const [family, alias] of Object.entries(config.claudeFamilyFallback)) {
        console.log(`  ${family.padEnd(8)} → ${alias}  →  ${config.modelMap[alias] || '(unknown)'}`);
      }
      console.log('----------------------------------------');
      console.log(` Visible /v1/models entries: ${(config.visibleModels || []).length}`);
      console.log(` Total aliases (incl. hidden): ${Object.keys(config.modelMap).length}`);
      console.log('========================================');
    });
  } catch (error) {
    console.error(`[${SERVER_NAME}] startup failed: ${error.message}`);
    process.exit(1);
  }
}
